apiVersion: batch/v1
kind: Job
metadata:
  name: jobname
spec:
  template:
    metadata:
      labels:
        app: gotest
    spec:
      containers:
      - name: counter
        image: centos:7
        command:
          - "bin/bash"
          - "-c"
          - "curl http://my-service:8080"
      restartPolicy: Never
