apiVersion: batch/v1
kind: Job
metadata:
  name: jobname
spec:
  template:
    metadata:
      name: podname
    spec:
      containers:
      - name: counter
        image: centos:7
        command:
          - "bin/bash"
          - "-c"
          - "echo rakesh"
      restartPolicy: Never



